/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IntentChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bets"
      | "intentCount"
      | "intents"
      | "nexusToken"
      | "owner"
      | "publishIntent"
      | "renounceOwnership"
      | "reputationScore"
      | "resolveIntent"
      | "stakeOnIntent"
      | "submitProof"
      | "transferOwnership"
      | "voters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IntentPublished"
      | "IntentResolved"
      | "OwnershipTransferred"
      | "ProofSubmitted"
      | "StakePlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bets",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "intents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nexusToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishIntent",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveIntent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeOnIntent",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "intentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nexusToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeOnIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
}

export namespace IntentPublishedEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    creator: AddressLike,
    description: string,
    stakeAmount: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    creator: string,
    description: string,
    stakeAmount: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    creator: string;
    description: string;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentResolvedEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    completed: boolean,
    creatorPayout: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    completed: boolean,
    creatorPayout: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    completed: boolean;
    creatorPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [intentId: BigNumberish, proofLink: string];
  export type OutputTuple = [intentId: bigint, proofLink: string];
  export interface OutputObject {
    intentId: bigint;
    proofLink: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakePlacedEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    voter: AddressLike,
    supportYes: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    voter: string,
    supportYes: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    voter: string;
    supportYes: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntentChain extends BaseContract {
  connect(runner?: ContractRunner | null): IntentChain;
  waitForDeployment(): Promise<this>;

  interface: IntentChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bets: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        supportYes: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  intentCount: TypedContractMethod<[], [bigint], "view">;

  intents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        creator: string;
        description: string;
        category: string;
        deadline: bigint;
        stakeAmount: bigint;
        sageScore: bigint;
        resolved: boolean;
        completed: boolean;
        totalYesStakes: bigint;
        totalNoStakes: bigint;
        proofLink: string;
        hasProof: boolean;
      }
    ],
    "view"
  >;

  nexusToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  publishIntent: TypedContractMethod<
    [
      description: string,
      category: string,
      deadline: BigNumberish,
      stakeAmount: BigNumberish,
      sageScore: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationScore: TypedContractMethod<[], [string], "view">;

  resolveIntent: TypedContractMethod<
    [intentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeOnIntent: TypedContractMethod<
    [intentId: BigNumberish, supportYes: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [intentId: BigNumberish, proofLink: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voters: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        supportYes: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "intentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        creator: string;
        description: string;
        category: string;
        deadline: bigint;
        stakeAmount: bigint;
        sageScore: bigint;
        resolved: boolean;
        completed: boolean;
        totalYesStakes: bigint;
        totalNoStakes: bigint;
        proofLink: string;
        hasProof: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nexusToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishIntent"
  ): TypedContractMethod<
    [
      description: string,
      category: string,
      deadline: BigNumberish,
      stakeAmount: BigNumberish,
      sageScore: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveIntent"
  ): TypedContractMethod<[intentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeOnIntent"
  ): TypedContractMethod<
    [intentId: BigNumberish, supportYes: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [intentId: BigNumberish, proofLink: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "IntentPublished"
  ): TypedContractEvent<
    IntentPublishedEvent.InputTuple,
    IntentPublishedEvent.OutputTuple,
    IntentPublishedEvent.OutputObject
  >;
  getEvent(
    key: "IntentResolved"
  ): TypedContractEvent<
    IntentResolvedEvent.InputTuple,
    IntentResolvedEvent.OutputTuple,
    IntentResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "StakePlaced"
  ): TypedContractEvent<
    StakePlacedEvent.InputTuple,
    StakePlacedEvent.OutputTuple,
    StakePlacedEvent.OutputObject
  >;

  filters: {
    "IntentPublished(uint256,address,string,uint256)": TypedContractEvent<
      IntentPublishedEvent.InputTuple,
      IntentPublishedEvent.OutputTuple,
      IntentPublishedEvent.OutputObject
    >;
    IntentPublished: TypedContractEvent<
      IntentPublishedEvent.InputTuple,
      IntentPublishedEvent.OutputTuple,
      IntentPublishedEvent.OutputObject
    >;

    "IntentResolved(uint256,bool,uint256)": TypedContractEvent<
      IntentResolvedEvent.InputTuple,
      IntentResolvedEvent.OutputTuple,
      IntentResolvedEvent.OutputObject
    >;
    IntentResolved: TypedContractEvent<
      IntentResolvedEvent.InputTuple,
      IntentResolvedEvent.OutputTuple,
      IntentResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofSubmitted(uint256,string)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "StakePlaced(uint256,address,bool,uint256)": TypedContractEvent<
      StakePlacedEvent.InputTuple,
      StakePlacedEvent.OutputTuple,
      StakePlacedEvent.OutputObject
    >;
    StakePlaced: TypedContractEvent<
      StakePlacedEvent.InputTuple,
      StakePlacedEvent.OutputTuple,
      StakePlacedEvent.OutputObject
    >;
  };
}
